---
title: "API Twitter"
author: "Zhanglin Shangguan"
date: "3/10/2020"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(jsonlite)
library(httr)
library(rvest)
library(ballr)
library(rtweet)
library(reactable)
library(glue)
library(twitteR)
library(ROAuth)
```


```{r}
twitter_app <- oauth_app("twitter",
  key = "KFxa563fmYmeFPmzWjOPMOXtY",
  secret = Sys.getenv("axgKvS5kJgXRycQrkba4dAF43bZs2DJqqtURgNZwInJwuc0AU4")
)
twitter_app

get_twitter_api <- function(endpoint, query = NULL) {
  signature <- oauth_signature(
    endpoint, 
    app = twitter_app,
    token = "581591154-o4RevQ6vSm4oczeftDqiKAxTpdPsKIBZ2UQ5wNaw",
    token_secret = Sys.getenv("MCuR5DUJWyenxiFDDzn9934hELwPV9ygpNFlxNIaP6lmh")
  )
  GET(endpoint, oauth_header(signature), query = query)
}



api_keys = "KFxa563fmYmeFPmzWjOPMOXtY"
api_secret = "axgKvS5kJgXRycQrkba4dAF43bZs2DJqqtURgNZwInJwuc0AU4"
token = "581591154-o4RevQ6vSm4oczeftDqiKAxTpdPsKIBZ2UQ5wNaw"
token_secret = "MCuR5DUJWyenxiFDDzn9934hELwPV9ygpNFlxNIaP6lmh"


```

```{r}

twitter_token <- oauth2.0_token(
  oauth_endpoint(
    authorize = NULL,
    access = "https://api.twitter.com/oauth2/token"
  ),
  twitter_app,
  client_credentials = TRUE
)

twitter_token <- create_token(
  app = "mytwitterapp",
  consumer_key = api_keys,
  consumer_secret = api_secret,
  access_token = token,
  access_secret = token_secret,
  set_renv = TRUE
)

```



```{r}
#Functions for making URL
make_url_html <- function(url) {
  if(length(url) < 2) {
    if(!is.na(url)) {
      as.character(glue("<a title = {url} target = '_new' href = '{url}'>{url}</a>") )
    } else {
      ""
    }
  } else {
    paste0(purrr::map_chr(url, ~ paste0("<a title = '", .x, "' target = '_new' href = '", .x, "'>", .x, "</a>", collapse = ", ")), collapse = ", ")
  }
}

```



```{r}
#API access 

setup_twitter_oauth(api_keys, api_secret, token, token_secret)

tweets <- search_tweets("James Harden" , n = 200, include_rts = FALSE,token = twitter_token)

searchTwitter("James Harden")
search_tweets("James Harden")

tweets <- search_tweets("James Harden" , n = 50, include_rts = FALSE) %>%
  select(user_id, status_id, created_at, screen_name, text,
         favorite_count,retweet_count,urls_expanded_url) %>%
  select(created_at, status_id,screen_name, text, favorite_count,
        retweet_count,urls_expanded_url )%>%
  mutate(
    Tweet = glue::glue("{text} <a href='https://twitter.com/{screen_name}/status/{status_id}'>>> </a>") 
    )%>%
  select(DateTime = created_at, User = screen_name, Tweet, Likes = favorite_count, RTs = retweet_count, URLs = urls_expanded_url) %>%
  mutate(URLS <- purrr::map_chr(tweets$URLs, make_url_html)) %>% tibble()
tweets

tweets_table$URLs <- purrr::map_chr(tweets_table$URLs, make_url_html)
tweets_table


get_trends("lebron")

#In Shiny Apps, we can use the follwoing code to obtain reactable
# library(reactable)
# 
# ui <- fluidPage(
#  titlePanel("reactable example"),
#  reactableOutput("table")
# )
# 
# server <- function(input, output, session) {
#   output$table <- renderReactable({
#    reactable(iris)
#  })
# }




reactable(tweets_table, 
          filterable = TRUE, searchable = TRUE, bordered = TRUE, striped = TRUE, highlight = TRUE,
          showSortable = TRUE, defaultSortOrder = "desc", defaultPageSize = 25, showPageSizeOptions = TRUE, pageSizeOptions = c(25, 50, 75, 100, 200), 
          columns = list(
            DateTime = colDef(defaultSortOrder = "asc"),
            User = colDef(defaultSortOrder = "asc"),
            Tweet = colDef(html = TRUE, minWidth = 190, resizable = TRUE),
            Likes = colDef(filterable = FALSE, format = colFormat(separators = TRUE)),
            RTs = colDef(filterable =  FALSE, format = colFormat(separators = TRUE)),
            URLs = colDef(html = TRUE)
          )
) 


```

```{r}





```



```{r}


```

```{r}


```


```{r}


```



```{r}


```


```{r}


```



```{r}


```



```{r}


```



```{r}


```



```{r}


```


```{r}


```