---
title: "nbastatsscrape"
author: "John Tran"
date: "February 26, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(rvest)
library(devtools)
library(jsonlite)

```

## Web Scrapping part

```{r cars}
nba <-read_html("https://www.basketball-reference.com/leagues/NBA_2020_per_game.html") 
nba_table <- html_table(nba)
player_stats <- data.frame(nba_table)
player_stats <- player_stats %>% mutate_at(vars(Rk,Age,G,GS,MP,FG,FGA,FG.,X3P,X3PA,X3P.,X2P,eFG.,FT,FTA,FT.,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS),funs(as.numeric)) %>% drop_na
a <- player_stats %>%  group_by(PTS) %>% arrange(desc(PTS))
a
```

## NBA API
Trying for the API have not gotten it yet

```{r}
r <-(" https://api-nba-v1.p.rapidapi.com/games/league/standard/2020")
headers(r)
httr::http_status(r)
json <- content(r,as = "text")
json
a <- fromJSON(json)
a
a$message
```




```{r}

library("ballr")

playerdata <- NBAPerGameStatistics(season = 2020)
names(playerdata)
playerdata %>% select(player,pos,mp,trb,ast,stl,blk,tov,pf,pts)
playerdata[1,]
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
